### ISSUE TITLE
implement method provideCreatePaymentHandler

### ISSUE THREAD

**Issue by MGA-dotSource** [commercetools/commercetools-sunrise-java-payment#10]
method should return a function that can then be executed by the PaymentAdapterService

The method should be payment method specific (as needed).

It'll take a parameter that is a data holding wrapper object providing all possibly necessary information the shop could deliver.

- current cart (required)
- current customer (optional)
- current http request information (create a new data holding object as the shops HTTP technology stack is unknown)

It'll return a wrapper object containing

- status information of the process (succeeded, failed, error msg)
- optional the created payment object (CTP)
- task object for the shop to know what to do now (nothing, redirect, other)
- data for the task object like redirect URL or any possibly needed information

**Comment by butenkor** [comment]
customer is optional so if it is not provided you are going to fetch it with help of cart's ```customerId```?

**Comment by butenkor** [comment]
```current http request``` What exactly do you need besides user IP?

**Comment by MGA-dotSource** [comment]
@butenkor customer is optional cause it is basically not required to create a valid payment object as the cart has all needed data (names, addresses, etc.). This parameter is more something for the future as we're building an extensible and mostly generic framework. Maybe there'll be a PSP that needs a customer beeing logged in..

The HTTPRequestInfo (that's what the class is called now) provides possible information of IPv4 and IPv6 addresses and the requests locale. Header attributes could be taken into account as well, but are not yet supported. All this is not needed for Payone but maybe for any other PSP..

The whole architecture tries to provide as much data as possible to the PSP implementations to make sure adding a new one doesn't require changes within the common library.

**Comment by MGA-dotSource** [comment]
general method implementation is done
Method specific stuff is done within issues #12 #13 #14
