### ISSUE TITLE
define and implement use case for Payone Paypal

### ISSUE THREAD

**Issue by MGA-dotSource** [commercetools/commercetools-sunrise-java-payment#13]
define what happens when, where and how if the users selectes Payone Paypal as his payment method

**Comment by MGA-dotSource** [comment]
data and user action flow needs to be implemented as following:

1. user selects "paypal" as his payment method
2. PaymentFramework creates Payment object @ CTP (success, cancel, error redirect URLs provided by the shop)
3. shop shows "buy now" button, user clicks it
6. create the transaction
7. call the "handlePayment" method of the Payone Connector
8. interpret the result -> get a valid payment object back
9. possibly a redirect URL is provided -> then redirect
10. handle callbacks after redirect accordingly
11. create order if everything worked fine
12. show confirmation page

**cancel** or **error** callbacks have to be handled by the shop and should probably result in the possibility to select a new payment method

**Comment by butenkor** [comment]
Looks good. Make sure you show some generic or specific error message to the customer if payone response is a failure (edge case). For credit card it may be that credit card is blacklisted or blocked. This information is included in interactions list of payment object.

**Comment by butenkor** [comment]
@mht-dotsource can it be closed?
