### ISSUE TITLE
handlePayment URL should be provided by the shop when calling payment connector

### ISSUE THREAD

**Issue by butenkor** [commercetools/commercetools-sunrise-java-payment#16]
It may be URL for staging or production instance

**Comment by MGA-dotSource** [comment]
Indeed this is kind of tricky as the shop is intended to basically know nothing about the available implementations.
But on the other hand it makes sense that the shop is leading for that kind of configuration.

As a quick solution the url has to be passed with every "create transaction" request as a config parameter called "PayoneHandleURL".
I do not really like that but concerning the current deadline this is the way to go for now.

@butenkor we should discuss that in depth later (maybe with @lauraluiz or @schleichardt)

**Comment by floriansattler** [comment]
@salander can you help here?

**Comment by butenkor** [comment]
It is ok to provide at as parameter.
