### ISSUE TITLE
Country specific config for payment methods

### ISSUE THREAD

**Issue by floriansattler** [commercetools/commercetools-sunrise-java-payment#5]
Config for payments needs to be done in a way that you are able to show different payment methods in the checkout based on the country selected in your billing address.

**Comment by MGA-dotSource** [comment]
This is a bigger task. 
First question: is (or should) the abstract framework be able to decide about allowed / not allowed countries?
If yes, then what are the rules?

If it is a shop responsibility then there is already a build in feature, that allows the shop to pass a filter function into the "getMethods" - API call that is executed every time where any kind of filtering is possible.

Filtering itself has to be discussed in more detail and is not in scope for the first iteration I think.
